language: python
python: 2.7
sudo: required
services:
- docker
matrix:
  fast_finish: true
before_script:
- ./linter.sh
script:
- ./build.sh
after_success:
- ./repo_build.sh
env:
  global:
    secure: "VMJP3AO9oeOiykLNoNCovuDGrW54BJWSHlbR/WGMVVqnzHmZIkaqXdxOVVF7k+f7kmN1DMIUM9kuHkdjsH1NjiVmMXJtHTLaQI6H4aUPTd5F1mKqZqlPL1BMvf0bmHvbJaYBDuK01FNAT4Mzj73IkEw3NYYZ4rrGCG1dN4JyvdqWt1K2i6EKOixN8DNff8tjnOcVWA6Ujeh+FdtIzFPJJMwGdXVuHvfOu5bqJxOSDPAZv+xU6x7xi+NaXqE7spFRidS3xpbjh0FZPVBP56bLCVJyvGGA8SK6BfFfy0RCVdrS5vOvT+tXGmfBVILeqkVQhSy8O5JHPZ8QA6Z+qlpDf6zkPQqL4ykIr8O1B+8jdikaPbz61A2/lXQGcM4w1D5OmoJRRnG9zhKgllTYY1rIY3pO9PiE36WelJEQdqvL5ARPlYVqbBN2xbCmu8WmwSzzemRpSqsooAlDInm191asiw8lQfph25H6bHB589r8j1D3ud9nx/LWbk+9LUbH8hOuTNEnhwmBUUUq8Wk0i5LW3Icx4QeCMKcgk5gPYaBuYJft7Z10TeIZOLNUoGLPtd9NKCTPjaSF12RO83oNJ2qRq2RaNhlsx+GC63K7NKibGW7UhF6+Hwkt9yzJHjSCZOvoDTsgZACXUqf06IjcUFYssJcm2AfRM/a0ruEAab//6b0="