language: python
python: 2.7
sudo: required
services:
- docker
matrix:
  fast_finish: true
before_script:
- ./linter.sh
script:
- ./build.sh
after_success:
- ./repo_build.sh
env:
  global:
  - secure: VMJP3AO9oeOiykLNoNCovuDGrW54BJWSHlbR/WGMVVqnzHmZIkaqXdxOVVF7k+f7kmN1DMIUM9kuHkdjsH1NjiVmMXJtHTLaQI6H4aUPTd5F1mKqZqlPL1BMvf0bmHvbJaYBDuK01FNAT4Mzj73IkEw3NYYZ4rrGCG1dN4JyvdqWt1K2i6EKOixN8DNff8tjnOcVWA6Ujeh+FdtIzFPJJMwGdXVuHvfOu5bqJxOSDPAZv+xU6x7xi+NaXqE7spFRidS3xpbjh0FZPVBP56bLCVJyvGGA8SK6BfFfy0RCVdrS5vOvT+tXGmfBVILeqkVQhSy8O5JHPZ8QA6Z+qlpDf6zkPQqL4ykIr8O1B+8jdikaPbz61A2/lXQGcM4w1D5OmoJRRnG9zhKgllTYY1rIY3pO9PiE36WelJEQdqvL5ARPlYVqbBN2xbCmu8WmwSzzemRpSqsooAlDInm191asiw8lQfph25H6bHB589r8j1D3ud9nx/LWbk+9LUbH8hOuTNEnhwmBUUUq8Wk0i5LW3Icx4QeCMKcgk5gPYaBuYJft7Z10TeIZOLNUoGLPtd9NKCTPjaSF12RO83oNJ2qRq2RaNhlsx+GC63K7NKibGW7UhF6+Hwkt9yzJHjSCZOvoDTsgZACXUqf06IjcUFYssJcm2AfRM/a0ruEAab//6b0=
  - secure: jHoIOy3SFD8QQHA6F3OmvDUdydpZIao9+L3tFMUtkpBaWz0h10xQwzIvV9w9zbTeNnmmR2jVbAUyDBibVJBWa5akEynDrKeyWBL1GjY98XUBH+Qw6MFUZ1ovHCDIxmdaO0HS+GsfLtY59iBREyJp8qkOexDVEl8LaaaLY0s57ZHI/7AoQ+RvvqbVZDsKPWzu2uKOIowQID8+zAyO7FLrliomk3rpVx+qczSeYDscahUeFsVRbQ90383GSh958+8LPIiXQTWDihaYqml9vms7c9KcW1DQtHgmJkVHyuR4KrOL6luT1nE347fhWl8SbNPG92aBGeYOnOu+Jiymur18yYyS9iTOKlTLw6JVlbWHpSi4zMV6+lhAw6dzIkxtjp9P0N2mIiC0o1t+D1gbcguU8fXy47QpDVTZiV3Ix0fj/byizk0u8avLLzszuRtQsBhvimjBqjt1PiXLa6ra86/fgrDlyONrHX5qAXxBziu8t8m5Tr5pW+LWkHHc7ydhKjoy62r5rE8CO90kc7wz5KsHJD9vyehxf7SXOCnTNdSzyS/pVYGnjrbeTtBg0wY6O13XFPixNlKRe152hIxVRvuZ9UZey0P3T7hnu/RCqOf/iLtjD0qdmQ7/5Co7BG+Qhg/Jo/ltS7y/ItNPGKjrXA4rGGF44Nj+tUyMZdj6WS5aFoM=
