version: '2'
services:
  haproxy:
    image: eeacms/haproxy
    restart: 'always'
    depends_on:
      - limesurvey
    ports:
      - 8085:5000
      - 1937:1936
    environment:
      - BACKENDS=limesurvey
      - BACKENDS_PORT=80
      - SERVICE_NAMES=limesurvey
      - DNS_ENABLED=true
      - STATS_AUTH=admin:admin
      - COOKIES_ENABLED=true


  mysqldb:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    hostname: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: pesquisas
      MYSQL_USER: user
      MYSQL_PASSWORD: senha

  limesurvey:
    depends_on:
      - mysqldb
    volumes:
      - upload:/app/upload
    image:
      unixelias/limesurvey:dev
volumes:
  mysql:
  upload:
