version: '2'
services:
  limesurvey:
    ports:
      - "8085:80"
    volumes:
      - mysql:/var/lib/mysql
      - upload:/app/upload
    environment:
      - MYSQL_ROOT_PASSWORD = toor
      - MYSQL_DATABASE = lamp
      - MYSQL_USER = user
      - MYSQL_PASSWORD = passwd
    image:
      unixelias/limesurvey:latest
volumes:
  mysql:
  upload: