version: '2'
services:
  mysql:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: toor

  limesurvey:
    links:
      - mysql
    ports:
      - "8085:80"
    volumes:
      - upload:/app/upload
    image:
      unixelias/limesurvey:dev
      
volumes:
  mysql:
  upload:
