version: '2'
services:
  mysqldb:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    hostname: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: pesquisas
      MYSQL_USER: user
      MYSQL_PASSWORD: senha

  limesurvey:
    links:
      - mysqldb:mysqldb
    ports:
      - "8085:80"
    volumes:
      - upload:/app/upload
    image:
      unixelias/limesurvey:dev
volumes:
  mysql:
  upload:
