version: '2'
services:
  limesurvey:
    ports:
      - "8085:80"
    volumes:
      - mysql:/var/lib/mysql
      - upload:/app/upload
    image:
      unixelias/limesurvey:dev
volumes:
  mysql:
  upload: